[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/tendermint/go-amino"
  version = "0.10.1"

[[constraint]]
  name = "github.com/tendermint/tmlibs"
  version = "0.9.0-rc1"

[prune]
  go-tests = true
  unused-packages = true
