[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/tendermint/go-amino"
  version = "^0.12.0-rc0"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "^v0.26.0-dev0"

[prune]
  go-tests = true
  unused-packages = true
