version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.13
  protoc:
    docker:
      - image: tendermintdev/docker-protoc

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run:
          name: test
          command: |
            make test
      - run:
          name: tools
          command: make tools
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  proto-lint:
    executor: protoc
    steps:
      - checkout
      - run:
          command: make proto-lint
  proto-breakage:
    executor: protoc
    steps:
      - checkout
      - run:
          command: make proto-check-breaking

workflows:
  version: 2
  test-suite:
    jobs:
      - build
      - proto-lint
      - proto-breakage
